# Generated by Django 5.0.4 on 2026-04-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=50)),
                ('speciality', models.TextField()),
                ('licenses', models.TextField(blank=True)),
                ('expertise_tags', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['region', 'name'],
            },
        ),
    ]
