# Generated by Django 5.0.4 on 2026-04-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeverityThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('hull', 'Hull'), ('liability', 'Liability'), ('marine_cargo', 'Marine Cargo')], max_length=20, unique=True)),
                ('low_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medium_max', models.DecimalField(decimal_places=2, max_digits=12)),
                ('critical_description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['claim_type'],
            },
        ),
    ]
