server {
    listen 80;
    server_name team-solo-1-workshop.i2go.io;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name team-solo-1-workshop.i2go.io;

    # Managed by Certbot
    # ssl_certificate and ssl_certificate_key will be inserted here by certbot

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 60;
    }
}
